### ISSUE TITLE
Unable to import module 'index': Error

### ISSUE THREAD

**Issue by schwartzMS** [box-community/sample-document-skills#3]
I was able to clone and deploy the Skill but when I upload a file, I receive the following error in my CloudWatch logs: 

```
Unable to import module 'index': Error
at Function.Module._resolveFilename (module.js:547:15)
at Function.Module._load (module.js:474:25)
at Module.require (module.js:596:17)
at require (internal/module.js:11:18)
at Object.<anonymous> (/var/task/utils/rossum.js:2:15)
at Module._compile (module.js:652:30)
at Object.Module._extensions..js (module.js:663:10)
at Module.load (module.js:565:32)
at tryModuleLoad (module.js:505:12)
at Function.Module._load (module.js:497:3)
```

Any thoughts?

**Comment by cbetta** [comment]
@schwartzMS I assume you mean the Rossum skill (as there's only one in this repo for now). @PhilMayer can you have a look and confirm.

**Comment by PhilMayer** [comment]
Thanks for the heads up @cbetta and @schwartzMS. I'm looking into it this afternoon.

**Comment by schwartzMS** [comment]
@PhilMayer from inside the rossum-voice-intelligence

**Comment by PhilMayer** [comment]
@schwartzMS gotcha. Also just want to make absolutely sure you `npm install`ed before deploying?

**Comment by cbetta** [comment]
Found the issue and fixed it
